sudo: false

language: node_js

node_js:
  - "8"
  - "lts/*"
  - "node"

cache:
  directories:
    - node_modules
    - $HOME/.npm

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
